### ISSUE TITLE
Glitches in Quick Start?

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/amplpy#19]
The following were noted by a user in the Python Quick Start section:

(1) ampl.read references models/diet/diet.mod but the standard AMPL distribution has this file in models/diet.mod (there is no 'diet' directory). Similarly for ampl.readData.

(2) The objective in the diet model is Total_Cost, rather than total_cost as referenced by ampl.getObjective.

Other Quick Start sections might also be affected.

**Comment by fdabrandao** [comment]
Hi Bob,

The examples mentioned in the documentation are the examples in the models folder or the API (https://github.com/ampl/amplpy/tree/master/models) and not of the models folder than comes with AMPL. In the folder that comes with the APIs, model and data files are grouped by type in different folders.

In the diet.mod that comes with the API (https://github.com/ampl/amplpy/blob/master/models/diet/diet.mod), the objective is total_cost instead of Total_Cost but it looks like it has always been like that since the beginning.

Since having a folder called models with a slightly different content than the one that comes with AMPL is confusing, documentation and examples for every API need to be updated. I will open another issue for the internal API related to this.

**Comment by mapgccv** [comment]
Hi all, I guess we can have two courses of action:
1) use the models folder that comes with AMPL for the API examples as well. I'm not too fond of this as we will have models and API in separate repositories, hence it would be a bit more difficult to maintain consistency. Not to mention that as a programmer I would probably not put the API contents in the AMPL directory, relying instead on system search paths to find the AMPL interpreter. So, distributing the models with the API seems to me a necessity.
2) Update the documentation to clearly state this distinction
3) Change name of the directory (maybe from `models` to `apimodels`)
4) A combination (2) and (3)

I would probably vote for 4, but I'm open to other suggestions as well.

**Comment by fdabrandao** [comment]
I would vote for a change in the structure of the models folder that comes with the API to match the structure and the content of the models folder that comes with AMPL but just for the files are come with both such as diet.mod (i.e., move `models/diet/diet.mod` and `models/diet/diet.dat` to `models/diet.mod` and `models/diet.dat`). This requires changes in the documentation, in the examples, and in the tests, but it would allow users to use either folder without any issues.

This is particularly important for users that install amplpy with `pip install amplpy` and that may not know where to find the models folder that comes with the API and that may want to use the models folder that comes with AMPL.
