### ISSUE TITLE
Support for Bonmin solver in amplpy

### ISSUE THREAD

**Issue by amar123deep** [ampl/amplpy#2]
I am new to non linear optimisation area. My problem is formulated as Mixed Integer Non-linear programming. After checking online I found I can use bonmin solver on ampl webpage. Is there support for bonmin solver in amplpy as well? Can you please point out some examples? Thanks!

**Comment by fdabrandao** [comment]
You can use amplpy with any solver that is supported by AMPL. If in order to use `bonmin` with AMPL you use `option solver bonmin;`, you can switch the solver to `bonmin` in amplpy with `ampl.option['solver'] = 'bonmin'`.
```python
from amplpy import AMPL
ampl = AMPL()
ampl.read('model.mod')
ampl.option['solver'] = 'bonmin'
ampl.solve()
```
Note that you need to donwload the bonmin binary for your platform from http://ampl.com/products/solvers/open-source/ and place it in the AMPL folder before being able to use it in AMPL.
